import type { INodeProperties } from 'n8n-workflow';

export const auditLogsDirectoryAuditDescription: INodeProperties[] = [
		{
			"displayName": "Operation",
			"name": "operation",
			"type": "options",
			"noDataExpression": true,
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					]
				}
			},
			"options": [
				{
					"name": "Audit Logs List Directory Audits",
					"value": "Audit Logs List Directory Audits",
					"action": "List directoryAudits",
					"description": "Get the list of audit logs generated by Azure Active Directory (Azure AD). This includes audit logs generated by various services within Azure AD, including user, app, device and group Management, privileged identity management (PIM), access reviews, terms of use, identity protection, password management (SSPR and admin password resets), and self service group management.",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/auditLogs/directoryAudits"
						}
					}
				},
				{
					"name": "Audit Logs Create Directory Audits",
					"value": "Audit Logs Create Directory Audits",
					"action": "Create new navigation property to directoryAudits for auditLogs",
					"description": "Create new navigation property to directoryAudits for auditLogs",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/auditLogs/directoryAudits"
						}
					}
				},
				{
					"name": "Audit Logs Delete Directory Audits",
					"value": "Audit Logs Delete Directory Audits",
					"action": "Delete navigation property directoryAudits for auditLogs",
					"description": "Delete navigation property directoryAudits for auditLogs",
					"routing": {
						"request": {
							"method": "DELETE",
							"url": "=/auditLogs/directoryAudits/{{$parameter[\"directoryAudit-id\"]}}"
						}
					}
				},
				{
					"name": "Audit Logs Get Directory Audits",
					"value": "Audit Logs Get Directory Audits",
					"action": "Get directoryAudits from auditLogs",
					"description": "Get directoryAudits from auditLogs",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/auditLogs/directoryAudits/{{$parameter[\"directoryAudit-id\"]}}"
						}
					}
				},
				{
					"name": "Audit Logs Update Directory Audits",
					"value": "Audit Logs Update Directory Audits",
					"action": "Update the navigation property directoryAudits in auditLogs",
					"description": "Update the navigation property directoryAudits in auditLogs",
					"routing": {
						"request": {
							"method": "PATCH",
							"url": "=/auditLogs/directoryAudits/{{$parameter[\"directoryAudit-id\"]}}"
						}
					}
				}
			],
			"default": ""
		},
		{
			"displayName": "GET /auditLogs/directoryAudits",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs List Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "Top",
			"name": "%24top",
			"description": "Show only the first n items",
			"default": 50,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "$top",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs List Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "Skip",
			"name": "%24skip",
			"description": "Skip the first n items",
			"default": 0,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "$skip",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs List Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "Search",
			"name": "%24search",
			"description": "Search items by search phrases",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "$search",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs List Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "Filter",
			"name": "%24filter",
			"description": "Filter items by property values",
			"default": "",
			"type": "string",
			"routing": {
				"send": {
					"type": "query",
					"property": "$filter",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs List Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "Count",
			"name": "%24count",
			"description": "Include count of items",
			"default": true,
			"type": "boolean",
			"routing": {
				"send": {
					"type": "query",
					"property": "$count",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs List Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "Orderby",
			"name": "%24orderby",
			"description": "Order items by property values",
			"default": "[\n  null\n]",
			"type": "json",
			"routing": {
				"send": {
					"type": "query",
					"property": "$orderby",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs List Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "Select",
			"name": "%24select",
			"description": "Select properties to be returned",
			"default": "[\n  null\n]",
			"type": "json",
			"routing": {
				"send": {
					"type": "query",
					"property": "$select",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs List Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "Expand",
			"name": "%24expand",
			"description": "Expand related entities",
			"default": "[\n  null\n]",
			"type": "json",
			"routing": {
				"send": {
					"type": "query",
					"property": "$expand",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs List Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "POST /auditLogs/directoryAudits",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs Create Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "POST /auditLogs/directoryAudits<br/><br/>There's no body available for request, kindly use HTTP Request node to send body",
			"name": "operation",
			"type": "notice",
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs Create Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "DELETE /auditLogs/directoryAudits/{directoryAudit-id}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs Delete Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "If Match",
			"name": "If-Match",
			"description": "ETag",
			"default": "",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"If-Match": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs Delete Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "GET /auditLogs/directoryAudits/{directoryAudit-id}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs Get Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "Select",
			"name": "%24select",
			"description": "Select properties to be returned",
			"default": "[\n  null\n]",
			"type": "json",
			"routing": {
				"send": {
					"type": "query",
					"property": "$select",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs Get Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "Expand",
			"name": "%24expand",
			"description": "Expand related entities",
			"default": "[\n  null\n]",
			"type": "json",
			"routing": {
				"send": {
					"type": "query",
					"property": "$expand",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs Get Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "PATCH /auditLogs/directoryAudits/{directoryAudit-id}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs Update Directory Audits"
					]
				}
			}
		},
		{
			"displayName": "PATCH /auditLogs/directoryAudits/{directoryAudit-id}<br/><br/>There's no body available for request, kindly use HTTP Request node to send body",
			"name": "operation",
			"type": "notice",
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Audit Logs Directory Audit"
					],
					"operation": [
						"Audit Logs Update Directory Audits"
					]
				}
			}
		},
];
